name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '20'
          cache: 'npm'

      - name : npm install, build and test
        run: |
          npm install 
          npm run build --if-present
          npm run test --if-present
    
      
      - name: serve
        run: npm run serve
