name: Learn Github Actions
run-name: ${{ github.actor }} is learning GitHub Actions

on: 
  push:  
  branches: [ zeroPoint/parcel ]
  
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install